from typing import Optional, TypeVar

T = TypeVar('T')

def make_cache_value(result: T, ttl: Optional[float]) -> T: ...
def is_cache_value_valid(value: T) -> bool: ...
def retrieve_result_from_cache_value(value: T) -> T: ...
