from typing import Optional, Tuple, TypeVar

T = TypeVar('T')
CacheValue = Tuple[T, float]

def make_cache_value(result: T, ttl: Optional[float]) -> CacheValue[T]: ...
def is_cache_value_valid(value: CacheValue[T]) -> bool: ...
def retrieve_result_from_cache_value(value: CacheValue[T]) -> T: ...
